### ISSUE TITLE
CSRF token missing bij het uploaden van een profielfoto

### ISSUE THREAD

**Issue by sander1946** [rubentalstra/bak-counter#68]
de volgende error krijg je als je een afbeelding of gif upload als profiel foto, zowel bij jpg als png als gif.
```
Error: CSRF token missing
    at checkCsrf (/node_modules/lusca/lib/csrf.js:169:18)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node_modules/express/lib/router/index.js:328:13)
    at /node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/node_modules/express/lib/router/index.js:346:12)
    at next (/node_modules/express/lib/router/index.js:280:10)
    at Immediate.<anonymous> (/node_modules/express-session/index.js:514:7)
    at process.processImmediate (node:internal/timers:480:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by rubentalstra** [comment]
https://github.com/rubentalstra/bak-counter/pull/69
